django_crud/urls.py
from django.contrib import admin
from django.template.context_processors import media
from django.urls import path
from crudapplication import views
from django_crud import settings

from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.show),
                  path('emp', views.emp),
                  path('show', views.show),
                  path('edit/<int:id>', views.edit),
                  path('update/<int:id>', views.update),
                  path('delete/<int:id>', views.delete),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crudapplication/models.py
from django.db import models


class Employee(models.Model):
    eid = models.CharField(max_length=20)
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    econtact = models.CharField(max_length=15)
    eimage = models.FileField(upload_to="document/")

    class Meta:
        db_table = "employee"

crudapplication/forms.py
from django import forms
from crudapplication.models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

crudapplication/views.py
from django.shortcuts import render, redirect
from crudapplication.forms import EmployeeForm
from crudapplication.models import Employee


def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.save()
                return redirect("/show")
            except:
                pass
    else:
        form = EmployeeForm()
        return render(request, "index.html", {'form': form})


def show(request):
    employees = Employee.objects.all()
    return render(request, "show.html", {'employees': employees})


def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request, "edit.html", {'employee': employee})


def update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance=employee)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(request, "edit.html", {'employee': employee})


def delete(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect("/show")

crudapplication/templates/edit.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>

    <!-- Icons font CSS-->
    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper">
        <div class="wrapper wrapper--w680">
            <div class="card card-1">
                <div class="card-body">
                    <h2 class="title">Update Details</h2>
                    <form method="POST" action="/update/{{ employee.id }}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="input-group">
                            <label> Contact ID: </label>
                            <input class="input--style-1" type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label> Contact Name: </label>
                                    <input class="input--style-1" type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}"/>
                                </div>
                            </div>
                         </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label> Contact Email: </label>
                                    <input class="input--style-1" type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}"/>
                                </div>
                            </div>
                         </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label> Contact Phone: </label>
                                    <input class="input--style-1" type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}"/>
                                </div>
                            </div>
                         </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label> Image: </label>
                                    <input class="input--style-1" type="file" name="eimage" id="id_eimage" required value="{{ employee.eimage }}"/>
                                </div>
                            </div>
                         </div>

                            <!--
                            <div class="col-2">
                                <div class="input-group">
                                    <div class="rs-select2 js-select-simple select--no-search">
                                        <select name="gender">
                                            <option disabled="disabled" selected="selected">GENDER</option>
                                            <option>Male</option>
                                            <option>Female</option>
                                            <option>Other</option>
                                        </select>
                                        <div class="select-dropdown"></div>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="input-group">
                            <div class="rs-select2 js-select-simple select--no-search">
                                <select name="class">
                                    <option disabled="disabled" selected="selected">CLASS</option>
                                    <option>Class 1</option>
                                    <option>Class 2</option>
                                    <option>Class 3</option>
                                </select>
                                <div class="select-dropdown"></div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <input class="input--style-1" type="text" placeholder="REGISTRATION CODE" name="res_code">
                                </div>
                            </div>
                        </div>-->
                        <div class="p-t-20">
                            <button class="btn btn--radius btn--green" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'js/global.js' %}"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

crudapplication/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Contact Book</title>

    <!-- Icons font CSS-->
    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper p-t-100 p-b-100 font-robo">
        <div class="wrapper wrapper--w680">
            <div class="card card-1">
                <div class="card-body">
                    <h2 class="title">Enter Details</h2>
                    <form method="POST" action="/emp" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="input-group">
                            <label> Contact ID: </label>
                            {{ form.eid }}
                            <!--<input class="input--style-1" type="text" placeholder="NAME" name="name">-->
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label> Contact Name: </label>
                                    {{ form.ename }}
                                    <!--<input class="input--style-1 js-datepicker" type="text" placeholder="BIRTHDATE" name="birthday">-->
                                </div>
                            </div>
                         </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label> Contact Email: </label>
                                    {{ form.eemail }}
                                    <!--<input class="input--style-1 js-datepicker" type="text" placeholder="BIRTHDATE" name="birthday">-->
                                </div>
                            </div>
                         </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label> Contact Phone: </label>
                                    {{ form.econtact }}
                                    <!--<input class="input--style-1 js-datepicker" type="text" placeholder="BIRTHDATE" name="birthday">-->
                                </div>
                            </div>
                         </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label> Image: </label>
                                    {{ form.eimage }}
                                    <!--<input class="input--style-1 js-datepicker" type="text" placeholder="BIRTHDATE" name="birthday">-->
                                </div>
                            </div>
                         </div>

                            <!--
                            <div class="col-2">
                                <div class="input-group">
                                    <div class="rs-select2 js-select-simple select--no-search">
                                        <select name="gender">
                                            <option disabled="disabled" selected="selected">GENDER</option>
                                            <option>Male</option>
                                            <option>Female</option>
                                            <option>Other</option>
                                        </select>
                                        <div class="select-dropdown"></div>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="input-group">
                            <div class="rs-select2 js-select-simple select--no-search">
                                <select name="class">
                                    <option disabled="disabled" selected="selected">CLASS</option>
                                    <option>Class 1</option>
                                    <option>Class 2</option>
                                    <option>Class 3</option>
                                </select>
                                <div class="select-dropdown"></div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <input class="input--style-1" type="text" placeholder="REGISTRATION CODE" name="res_code">
                                </div>
                            </div>
                        </div>-->
                        <div class="p-t-20">
                            <button class="btn btn--radius btn--green" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'js/global.js' %}"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

crudapplication/templates/show.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
<h2>Contact Book</h2>
  <p>List of Contacts Available in Database</p>
  <input class="form-control" id="myInput" type="text" placeholder="Search..">
  <br>
<table class="table table-responsive" id="example">
  <thead>
    <tr>
      <!--<th scope="col">Contact ID</th>-->
      <th scope="col">Contact Name</th>
      <th scope="col">Contact Email</th>
      <th scope="col">Contact Phone No.</th>
      <th scope="col">Image</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody id="myTable">
  {%  for employee in employees %}
    <tr>
      <!--<th scope="row">{{ employee.eid}}</th>-->
      <td>{{ employee.ename}}</td>
      <td>{{ employee.eemail}}</td>
      <td>{{ employee.econtact}}</td>
      <td><img src="{{ employee.eimage.url }}" height="100px" width="100px"/></td>
      <td>
          <a href="/edit/{{ employee.id }}" class="btn btn-primary">Edit</a>
          <a href="/delete/{{ employee.id }}" class="btn btn-danger">Delete</a>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
<br>

<a href="/emp" class="btn btn-primary align-right">Add Contact</a>
</div>


<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
<script>
    $(document).ready(function() {
    $('#example').DataTable();
} );
</script>

</body>
</html>